hCaptcha/hmt-basemodels

.travis.yml
Dockerfile

Fix travis

---

basemodels/__init__.py
setup.py
test.py

sync manifest with frontend, refactor, add realistic multi_challenge manifest test

---

Dockerfile
Pipfile
Pipfile.lock
README.md
basemodels/__init__.py
bin/lint
setup.py
test.py
yapf.cfg

old reuest_types dont work with new frontends

move request type to global and allow for multi choices in ilmc

---

Pipfile.lock
basemodels/manifest.py
setup.py

We'll need this to support payment to multiple different token addresses.

Add a field for HMTOKEN_ADDR

---

basemodels/manifest.py
setup.py

Closes https://github.com/hCaptcha/hmt-basemodels/issues/26
Also closes https://github.com/hCaptcha/hmt-basemodels/issues/27 since I stumbled upon that just now

require totaltasks

---

basemodels/manifest.py
test.py

Adds support for min_difficulty root, and other root items in the future.

allow unnested floats for min_difficulty

---

basemodels/manifest.py
setup.py
test.py

Closes https://github.com/IntuitionMachines/hmt-servers/issues/3542

enable the number types to be serialized

---

basemodels/manifest/data/preprocess.py
basemodels/manifest/manifest.py
basemodels/pydantic/__init__.py
basemodels/pydantic/manifest/data/preprocess.py
pyproject.toml
setup.py
tests/test_preprocess.py
tests/test_pydantic_preprocess.py

close #46
Add basic image preprocessing schema

Add preprocessing schema

---

basemodels/pydantic/manifest/manifest.py
pyproject.toml
setup.py
tests/test_pydantic.py

Generate unite job_id for manifest in pydantic models

Generate unite job_id for manifest in pydantic models

---

.travis.yml
basemodels/manifest/manifest.py
basemodels/manifest/restricted_audience.py
basemodels/pydantic/manifest/manifest.py
basemodels/pydantic/manifest/restricted_audience.py
pyproject.toml
setup.py
tests/both_models.py

Enforcing constrains on restricted_audience field

Add restricted_audience checks

---

basemodels/manifest/restricted_audience.py
basemodels/pydantic/manifest/restricted_audience.py
pyproject.toml
setup.py
tests/both_models.py

Add "modern_browser" option to manifest > restricted_audience > browser

Add modern_browser

---

basemodels/manifest/data/preprocess.py
basemodels/pydantic/manifest/data/preprocess.py
pyproject.toml
setup.py

Add ocr filter pipeline

---

basemodels/manifest/manifest.py
basemodels/pydantic/manifest/manifest.py
pyproject.toml
setup.py

close #65 
Add field to manifest holding url and count of rejected tasks

Add rejected tasks to manifest

---

basemodels/manifest/data/preprocess.py
basemodels/pydantic/manifest/data/preprocess.py
pyproject.toml
setup.py

closes #67
Add Upload pipeline for quick launch

Add Upload Pipeline

---

.travis.yml

Update python in travis to 3.7

---

.gitignore
basemodels/manifest/manifest.py
basemodels/pydantic/manifest/manifest.py
pyproject.toml
setup.py
tests/both_models.py

Add sensitivity for `request_config`

Add overlap_threshold config

---

basemodels/manifest/manifest.py
pyproject.toml
setup.py

This PR adds new fields to request_config to allow more information about IMOO text_free_entry kind of Jobs.

Add new fields to request config

---

basemodels/manifest/restricted_audience.py
basemodels/pydantic/manifest/restricted_audience.py
setup.py
tests/both_models.py

Related: https://github.com/IntuitionMachines/hmt-mono/pull/2156

RestrictedAudience: add interests

---

pyproject.toml
setup.py

Updating version to use ILMC `restricted_answer_set` check from #93

project: bump version to 0.1.28

---

basemodels/manifest/manifest.py
basemodels/pydantic/manifest/manifest.py
pyproject.toml
setup.py

New field "ignore_case" is added to RequestConfig

RequestConfig updates
